[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd packages/shared && npm run build && cd ../backend && npm run build"

[deploy]
startCommand = "cd packages/backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
